version: "3"
services:
  frontend:
    build: frontend
    depends_on:
      - api
    tty: true
    volumes:
      - ./frontend/public:/frontend/public:cached,ro
      - ./frontend/src:/frontend/src:cached,ro
    ports:
      - "3111:3000"
    depends_on: 
      - api
    env_file: 
       - ./.env
    environment:
      - REACT_PRODUCTION_TYPE=${REACT_PRODUCTION_TYPE}

  api:
    hostname: api-host
    build: backend
    depends_on:
      - database
    tty: true
    volumes:
      - ./backend/bin:/backend/bin:cached,ro
      - ./backend/src:/backend/src:cached,ro
    ports:
      - "3010:3010"
    depends_on:
      - database
    # environment:
    #   DATABASE_USER: "root"
    #   DATABASE_PASSWORD: "1234"
    #   DATABASE_URL : database

  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "root"
    #   MONGO_INITDB_ROOT_PASSWORD: "1234"
